version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb_container
    ports:
      - 27018:27017
    volumes:
      - mongodb_data:/mongodb/data
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30m
      timeout: 5s
      retries: 10
      start_period: 15s
    restart: unless-stopped
    networks:
      - app_network
  
  app:
    build: .
    container_name: app_container
    ports:
      - 8888:8888
    depends_on:
      - mongodb
    networks:
      - app_network

volumes:
  mongodb_data:

networks:
  app_network:
    driver: bridge
