version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb_container
    env_file:
      - .env
    ports:
      - 27018:27017
    volumes:
      - mongodb_data:/mongodb/data
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 1m
      timeout: 30s
      retries: 10
      start_period: 30s
    restart: unless-stopped
    networks:
      - app_network
  
  app:
    build: .
    container_name: app_container
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - mongodb
    networks:
      - app_network

volumes:
  mongodb_data:

networks:
  app_network:
    driver: bridge
