name: CI Pipeline

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
    workflow_dispatch:

jobs:
    AppAhmadishina:
        name: CI Pipline for App Ahmadishina
        runs-on: ubuntu-latest
        steps:
            - name: Start MongoDB
              uses: supercharge/mongodb-github-action@1.2.0

            - uses: actions/checkout@v2

            - name: Install dependencies
              run: npm install

            - name: Lint the codebase
              if: always()
              run: npm run lint

            - name: Test our code
              if: always()
              run: npm run test

            - name: Build
              if: always()
              run: npm run build
